# Site wide configuration

title:            SchaetzKc LLC
locale:           en_US
#url:  //gschaetz.github.io
url: https://www.schaetzkc.com 

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Gary Schaetz
  avatar: gary.jpg
  bio: "Code to live and live to Code."
  email: gary@schaetzkc.com
  disqus-shortname:
  twitter: #username
  facebook: gary.schaetz
  google:
    plus: #username
    analytics: UA-42842763-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: gschaetz
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: garyschaetz
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
